name: would-be-deleted


on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'
  workflow_dispatch:
    

defaults:
  run:
    shell: bash -l {0}

permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: atharva-2001/tardis-benchmark-test-results
        path: tbt_results

    - run: tree  ../ -L 4

    - run: git config --unset-all http.https://github.com/.extraheader
      working-directory: tbt_results
    

    - name: Create and push changes
      working-directory: tbt_results
      run: |
        echo "New content" >> README.md
        git config --global user.email "aryaatharva18@gmail.com"
        git config --global user.name "Atharva Arya"
        git add .
        git commit -m "test"
    
    - run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
    
    - run: |
        git push origin main