name: run-benchmarks

on:
  # push:
  #   branches:
  #   - '*'

  # pull_request:
  #   branches:
  #   - '*'
  workflow_dispatch:
  workflow_call:
    

defaults:
  run:
    shell: bash -l {0}

# permissions:
#       pages: write      # to deploy to Pages
#       id-token: write   # to verify the deployment originates from an appropriate source
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v4
      name: python
      with:
        python-version: '3.8' 
    
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        activate-environment: ""
        
    - name: Install asv
      run: pip install asv
    
    - run: asv machine --yes
    
    - name: Run benchmarks
      run: asv run --verbose
    
    - run: asv publish
    - run: git status

    # - run: git config --unset-all http.https://github.com/.extraheader

    # - name: Checkout repository
    #   uses: actions/checkout@v2
    #   with:
    #     repository: atharva-2001/tardis-benchmark-test-results
    #     path: tbt_results

    # - run: tree  ../ -L 4
    
    # - run: cp -r ../.asv .
    #   working-directory: tbt_results

    # - name: Create and push changes
    #   working-directory: tbt_results
    #   run: |
    #     git config --global user.email "aryaatharva18@gmail.com"
    #     git config --global user.name "Atharva Arya"
    #     git add .asv
    #     git commit -m "test"
    #     gh auth login --with-token <<< "${{ secrets.DEPLOY_PAT }}"
    #     gh repo view
    #     git push -u origin HEAD
    # - name: Pushes to another repository
    #   uses: cpina/github-action-push-to-another-repository@main
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.DEPLOY_PAT }}
    #   with:
    #     source-directory: .asv
    #     destination-github-username: atharva-2001
    #     destination-repository-name: tardis-benchmark-test-results
    #     user-email: aryaatharva18@gmail.com
    #     target-branch: main

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        token: ${{ secrets.DEPLOY_PAT }}

    # - uses: actions/upload-artifact@v2
    #   if: always()
    #   with:
    #     name: asv-benchmark-results-ubuntu-latest2
    #     path: .asv/results

    # - uses: actions/configure-pages@v1
    # - uses: actions/upload-pages-artifact@v1
    #   with:
    #     path: .asv/html

    # - name: Deploy to GitHub Pages
    #   id: deployment
    #   uses: actions/deploy-pages@v1
      # permissions:
      #   pages: write      # to deploy to Pages
      #   id-token: write   # to verify the deployment originates from an appropriate source
  # publish:
  #   uses: ./.github/workflows/publish.yml
    # needs: build
    # permissions:
    #   pages: write      # to deploy to Pages
    #   id-token: write
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/configure-pages@v1
    #   - uses: actions/upload-pages-artifact@v1
    #     with:
    #       path: .asv/html

    #   - name: Deploy to GitHub Pages
    #     id: deployment
    #     uses: actions/deploy-pages@v1
    