name: run-benchmarks

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

defaults:
  run:
    shell: bash -l {0}

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v4
      name: python
      with:
        python-version: '3.8' 
    
    - name: Install asv
      run: pip install asv
    
    - name: Run benchmarks
      run: asv run --environment existing:same --verbose
    
    - name: Publish changes
      run: asv publish
    